// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHledEZvkPHSKr7IAfPaIRjTc_1duKo64',
    appId: '1:314973879101:web:a9a873ae385c4f426ba354',
    messagingSenderId: '314973879101',
    projectId: 'behavioral-pattern',
    authDomain: 'behavioral-pattern.firebaseapp.com',
    storageBucket: 'behavioral-pattern.firebasestorage.app',
    measurementId: 'G-WLR3D37E8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoJSQbLJSWz1cmogWFpKCO96ToaP90aE',
    appId: '1:314973879101:android:fbadb18aa72e087b6ba354',
    messagingSenderId: '314973879101',
    projectId: 'behavioral-pattern',
    storageBucket: 'behavioral-pattern.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkfPxfEis--37LgO2Z2PIOOERV9yviwQ',
    appId: '1:314973879101:ios:52a0c274995c92306ba354',
    messagingSenderId: '314973879101',
    projectId: 'behavioral-pattern',
    storageBucket: 'behavioral-pattern.firebasestorage.app',
    iosBundleId: 'com.example.behavioralPattern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgkfPxfEis--37LgO2Z2PIOOERV9yviwQ',
    appId: '1:314973879101:ios:52a0c274995c92306ba354',
    messagingSenderId: '314973879101',
    projectId: 'behavioral-pattern',
    storageBucket: 'behavioral-pattern.firebasestorage.app',
    iosBundleId: 'com.example.behavioralPattern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHledEZvkPHSKr7IAfPaIRjTc_1duKo64',
    appId: '1:314973879101:web:709eac85828fd7936ba354',
    messagingSenderId: '314973879101',
    projectId: 'behavioral-pattern',
    authDomain: 'behavioral-pattern.firebaseapp.com',
    storageBucket: 'behavioral-pattern.firebasestorage.app',
    measurementId: 'G-4CBXFDR754',
  );

}